M48
; DRILL file {KiCad 7.0.7} date Sun Oct  1 15:31:46 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-01T15:31:46+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0295
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.2087
%
G90
G05
T1
X2.5225Y-4.6658
X2.5225Y-4.8942
T2
X3.67Y-4.06
T3
X2.45Y-2.975
X2.45Y-5.1
X5.65Y-2.975
X5.65Y-5.1
T0
M30
